config/routes.rb
Project::Application.routes.draw do
  devise_for :users

  match 'routes/:route_id/display' => 'halts#display', via: :get, as: :display_route_halts
  match 'routes/:route_id/halts/:id/register' => 'halts#register', via: [:get,:post], as: :register_route_halt
  match 'routes/:route_id/halts/:id/remove' => 'halts#remove', via: [:get,:post], as: :remove_route_halt
  match 'routes/:route_id/buses/:bus_id/assign' => 'buses#assign', via: [:get,:post], as: :assign_bus
  match 'routes/:route_id/halts/:id/assign_halt' => 'halts#assign_halt', via: [:get,:post], as: :assign_halt_route_halt
  match 'users/:id/menu' => 'users#menu', via: :get, as: :menu_user
  match 'buses/:bus_id/users/drivers' => 'users#drivers', via: :get, as: :drivers_bus_user
  match 'users/:user_id/buses/:bus_id/assign_driver' => 'users#assign_driver', via: :get, as: :assign_driver_bus_user
  match 'users/alert' => 'users#alert', via: :get, as: :alert_user
  
  resources :positions, only: [:edit, :update, :show, :destroy]
  
  resources :buses
  
  resources :halts
  
  resources :users do
    resources :positions, only: [:show]
    resources :buses
  end

  resources :routes do
    resources :buses
    resources :halts do 
      resources :buses
    end
  end

  
  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/halt.rb
class Halt < ActiveRecord::Base
	has_many :route_halts, dependent: :destroy
	has_many :routes, through: :route_halts
end

app/controllers/halts_controller.rb
class HaltsController < ApplicationController

  def new
    if !(params[:route_id].nil?)
   @route = Route.find(params[:route_id])
    else
   @halt= Halt.new
   end
  end

  def index
   if !(params[:route_id].nil?)
    @route= Route.find(params[:route_id])
    @halts = Halt.all
   else
    @halts = Halt.all
   end
  end

  def create
    if !(params[:route_id].nil?)
    @route = Route.find(params[:route_id])
    @bus = @route.bus
    @halt = @route.halts.create(params[:halt].permit(:halt_name, :bus_arrivetime, :bus_departtime, :title, :description).merge(:bus_id => @bus.id))
    redirect_to route_halt_path(@route,@halt)
    else
    @halt = Halt.create(params[:halt].permit(:halt_name, :bus_arrivetime, :bus_departtime, :title, :description))
    redirect_to halt_path(@halt)
    end  
  end

  def edit
    @halt = Halt.find(params[:id])
  end
 
  def update
    @halt = Halt.find(params[:id])
    if @halt.update_attributes(params[:halt].permit(:halt_name, :bus_arrivetime, :bus_departtime, :title, :description))
      flash[:success] = "Halt and its attibutes updated successfully"
      redirect_to halts_path
    else
      render 'edit'
    end
  end

  def destroy
    if params[:route_id].nil?  
      @halt = Halt.find(params[:id])
    else
      @route = Route.find(params[:route_id])
      @halt = @route.halts.find(params[:id])
    end
    if (@halt.destroy)
     flash[:success] = "Successfully deleted Halt"
     if !(params[:route_id].nil?)  
       redirect_to route_path(@route)
     else
       redirect_to halts_path
     end
   end
  end
  
  def show
  @halt = Halt.find(params[:id])
   if !(params[:route_id].nil?) 
   @route = Route.find(params[:route_id])
   @bus =@route.bus
   end
  end

   def display
    @r = Route.find(params[:route_id])
  end
   
   def remove
     @route = Route.find(params[:route_id])
    @halt = Halt.find(params[:id])
    @users = @halt.users
    if ((@halt.update_attributes :route_id => "NULL") && (@halt.save))
      @users.each do |user|
      if ((user.update_attributes :halt_id => "NULL") && (user.save))
      else
        redirect_to display_route_halts_path(@route)
      end
      end
       flash[:success] = "Successfully Removed Halt"
      redirect_to display_route_halts_path(@route)
    else
       redirect_to display_route_halts_path(@route)
    end
   end

  def register  
    @route = Route.find(params[:route_id])
    @halt = Halt.find(params[:id])
    @bus = @halt.bus
   if (@bus.bus_capacity > 0)
    if !(current_user.bus.nil?)
      @prev = current_user.bus
      @capacity = @prev.bus_capacity + 1

     if @prev.update_attributes bus_capacity: @capacity
      if ((current_user.update_attributes route: @route, halt: @halt, bus: @bus) && (current_user.save))
      @capacity= @bus.bus_capacity - 1
      if @bus.update_attributes bus_capacity: @capacity
      flash[:success] = "Successfully Registered for this Halt"
      redirect_to user_path(current_user)
      else
        redirect_to user_path(current_user)
      end
      else 
      redirect_to user_path(current_user)
      end
      else 
      redirect_to user_path(current_user)
      end
    else
      if ((current_user.update_attributes route: @route, halt: @halt, bus: @bus) && (current_user.save))
      @capacity= @bus.bus_capacity - 1
      if @bus.update_attributes bus_capacity: @capacity
      flash[:success] = "Successfully Registered for this Halt"
      redirect_to user_path(current_user)
      else 
      redirect_to user_path(current_user)
      end
      else 
      redirect_to user_path(current_user)
      end
    end
  else 
     Rails.logger.info(current_user.errors.messages.inspect)
     redirect_to user_path(current_user)
  end
 end

  def assign_halt
    @route= Route.find(params[:route_id])
    @halt= Halt.find(params[:id])
    @bus= @route.bus
    if ((@halt.update_attributes route: @route, bus: @bus) && (@halt.save))
       flash[:success] = "Successfully Assigned Halt To Route"
     end
    redirect_to route_halts_path(@route)
  end
end

app/helpers/halts_helper.rb
module HaltsHelper
end

app/views/halts/_form.html.erb
<% provide(:title, 'Add Halt') %>
<h1><font face="monotype corsiva">Add Halt For <%= @route.route_name %></font></h1>
<div class="row">
 <div class="span6 offset3">
    <%= form_for([@route, @route.halts.build]) do |f| %>
    <%#= render 'shared/error_messages_for_halts' %>

      <%= f.label :halt_name %>
      <%= f.text_field :halt_name %>

       <%= f.label :bus_arrivetime %>
      <%= f.text_field :bus_arrivetime %>

      <%= f.label :bus_departime %>
      <%= f.text_field :bus_departtime %>

      
      <%#= f.label :latitude %>
      <%#= f.text_field :latitude %>
  
      <%#= f.label :longitude %>
      <%#= f.text_field :longitude %>
  
      <%= f.label :description %>
      <%= f.text_area :description %>
  
      <%#= f.label :title %>
      <%#= f.text_field :title %>

      <%= f.submit "Add Halt", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/halts/_halt.html.erb

  <strong>
  <%= halt.halt_name %> -->
</strong>

app/views/halts/display.html.erb
<% provide(:title, 'Available halts on this route') %>
<h1>Available Halts on <%= @r.route_name %></h1>
<table class="table">
  <tr>
    <th>Halt Name</th>
    <th>Bus Capacity</th>
    <th>Bus Arrival</th>
    <th>Bus Departure</th>
    <% if current_user.job_type == "admin"  %>
    <th>Remove From Route</th>
    <% end %>
    <% if current_user.job_type != "Driver"  %>
    <th>Select</th>
    <% end %>
  </tr>
 
  <% @r.halts.each do |halt| %>
    <tr>
      <td><%= halt.halt_name %></td>
      <td><% if !(halt.bus.nil?) %>
        <%= halt.bus.bus_capacity %>
        <% else %>
        No Bus Assigned
      <% end %>
      <td><%= halt.bus_arrivetime %></td>
      <td><%= halt.bus_departtime %></td>
       <% if current_user.job_type == "admin"  %>
        <td><%= link_to "<i class='icon-remove icon-large'></i>".html_safe, remove_route_halt_path(@r,halt) %> </td>
       <% end %>
       <% if current_user.job_type != "Driver"  %>
       <% if current_user.halt != halt  %>
       <td><%= link_to 'Register', register_route_halt_path(@r,halt) %></td>
       <% else %>
       <td>Registered</td>
       <% end %>
       <% end %>
    </tr>
  <% end %>
</table>
<hr>
<%= link_to "My Menu", menu_user_path(current_user) %>

app/views/halts/edit.html.erb
<% provide(:title, 'Edit Halt') %>
<h1><font face="monotype corsiva">Edit Halt For route -- <%= @halt.route_id %></font></h1>
<div class="row">
 <div class="span6 offset3">
    <%= form_for(@halt) do |f| %>
    <%#= render 'shared/error_messages_for_halts' %>

      <%= f.label :halt_name %>
      <%= f.text_field :halt_name %>

       <%= f.label :bus_arrivetime %>
      <%= f.text_field :bus_arrivetime %>

      <%= f.label :bus_departtime %>
      <%= f.text_field :bus_departtime %>

      
      <%#= f.label :latitude %>
      <%#= f.text_field :latitude %>
  
      <%#= f.label :longitude %>
      <%#= f.text_field :longitude %>
  
      <%= f.label :description %>
      <%= f.text_area :description %>
  
      <%#= f.label :title %>
      <%#= f.text_field :title %>

      <%= f.submit "Edit Halt", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/halts/index.html.erb
<% provide(:title, 'All Available halts') %>
<% if !(@route.nil?) %>
<h1>Select Halt For <%= @route.route_name %></h1>
<% else %>
<h1>All Available Halts</h1>
<% end %>
<table class="table">
  <tr>
    <th>Route Name</th>
    <th>Halt Name</th>
    <th>Bus Capacity</th>
    <th>Bus Arrival</th>
    <th>Bus Departure</th>
    <% if current_user.job_type == "admin"  %>
    <% if (@route.nil?) %>
    <th>EDIT</th>
    <th>DESTROY</th>
    <% else %>
    <th>Select</th>
    <% end %>
    <% end %>
  </tr>
 
  <% @halts.each do |halt| %>
    <tr>
      <td>
        <% if !(halt.route.nil?) %>
        <%= halt.route.route_name %>
        <% else %>
        Not on any route
      <% end %>
      </td>
      <td><%= halt.halt_name %></td>
      <td><% if !(halt.bus.nil?) %>
        <%= halt.bus.bus_capacity %>
        <% else %>
        No Bus Assigned
      <% end %>
    </td>
      <td><%= halt.bus_arrivetime %></td>
      <td><%= halt.bus_departtime %></td>
      <% if current_user.job_type == "admin"  %>
      <% if (@route.nil?) %>
       <td><%= link_to 'Edit', edit_halt_path(halt) %></td>
       <td><%= link_to 'Destroy', halt_path(halt),
                    method: :delete, data: { confirm: 'This halt and all its attributes will be deleted.Are you sure?' } %></td>
      <% else %>
       <td><%= link_to 'Select', assign_halt_route_halt_path(@route,halt) %></td>
      <% end %>
      <% end %>
    </tr>
  <% end %>
</table>
<hr>
<%= link_to "My Menu", menu_user_path(current_user) %>
<% if !(@route.nil?) %>
<hr>
<%= render "halts/form" %>
<% else %>
|<%= link_to "Add New Halt", new_halt_path %>
<% end %>

app/views/halts/new.html.erb
<% provide(:title, 'Add Bus') %>
<h1><font face="monotype corsiva">Add Halt</font></h1>
<div class="row">
 <div class="span6 offset3">
    <%= form_for(@halt) do |f| %>
    <%#= render 'shared/error_messages_for_halts' %>

      <%= f.label :halt_name %>
      <%= f.text_field :halt_name %>

       <%= f.label :bus_arrivetime %>
      <%= f.text_field :bus_arrivetime %>

      <%= f.label :bus_departime %>
      <%= f.text_field :bus_departtime %>

      <%#= f.label :latitude %>
      <%#= f.text_field :latitude %>
  
      <%#= f.label :longitude %>
      <%#= f.text_field :longitude %>
  
      <%= f.label :description %>
      <%= f.text_area :description %>
  
      <%#= f.label :title %>
      <%#= f.text_field :title %>
 

      <%= f.submit "Add Halt", class: "btn btn-small btn-primary" %>
    <% end %>
  </div>
</div>

app/views/halts/show.html.erb
<% provide(:title, @halt.id) %>
<h3><font face="monotype corsiva" color= "blue">Following halt is added on <% if !(@route.nil?) %>
  <%=@route.route_name %>:<% end %></h3></font>
  <br>
	<table class="table">
  <tr>
    <th>Route Name</th>
    <th>Halt Name</th>
    <th>Bus</th>
    <th>Bus Arrival Time</th>
    <th>Bus Departure Time</th>
  </tr>
    <tr>
       <td>
        <% if !(@route.nil?) %>
        <%= @route.route_name %>
        <% else %>
        Not Assigned
        <% end %>
        </td>
        <td><%= @halt.halt_name %></td>
        <td>
          <% if !(@route.nil?) %>
          <%= @bus.bus_no %>
        <% else %>
        Not Assigned
        <% end %>
        </td>
      <td><%= @halt.bus_arrivetime %></td>
      <td><%= @halt.bus_departtime %></td>  
   </tr>
</table><br>
<% if !(@route.nil?) %>
<%= render @route.halts %>
<hr>
<br>
  <%= render "halts/form" %>
  <% end %>
<hr>
<%= link_to "Back To Routes", routes_path %>