config/routes.rb
Project::Application.routes.draw do
  devise_for :users

  match 'routes/:route_id/display' => 'halts#display', via: :get, as: :display_route_halts
  match 'routes/:route_id/halts/:id/register' => 'halts#register', via: [:get,:post], as: :register_route_halt
  match 'routes/:route_id/halts/:id/remove' => 'halts#remove', via: [:get,:post], as: :remove_route_halt
  match 'routes/:route_id/buses/:bus_id/assign' => 'buses#assign', via: [:get,:post], as: :assign_bus
  match 'routes/:route_id/halts/:id/assign_halt' => 'halts#assign_halt', via: [:get,:post], as: :assign_halt_route_halt
  match 'users/:id/menu' => 'users#menu', via: :get, as: :menu_user
  match 'buses/:bus_id/users/drivers' => 'users#drivers', via: :get, as: :drivers_bus_user
  match 'users/:user_id/buses/:bus_id/assign_driver' => 'users#assign_driver', via: :get, as: :assign_driver_bus_user
  match 'users/alert' => 'users#alert', via: :get, as: :alert_user
  
  resources :positions, only: [:edit, :update, :show, :destroy]
  
  resources :buses
  
  resources :halts
  
  resources :users do
    resources :positions, only: [:show]
    resources :buses
  end

  resources :routes do
    resources :buses
    resources :halts do 
      resources :buses
    end
  end

  
  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	belongs_to :role
  belongs_to :route_halt
  belongs_to :vehicle

	before_create :set_default_role

  private

  def set_default_role
    self.role ||= Role.find_by_name('traveller')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy]
  before_action :admin_user,     only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.where(id: params[:id]).first
    if @user_halt = @user.route_halt
      @route= @user_halt.route
      @hash = Gmaps4rails.build_markers(@user_halt.halt) do |halt, marker|
        marker.lat halt.latitude
        marker.lng halt.longitude
        marker.infowindow halt.description
      end
      @source = @route.route_halts.source
      @destination = @route.route_halts.destination
      @vehicle = @route.vehicle
    end
  end

  def drivers
    @bus= Bus.find(params[:bus_id])
    @drivers = User.where(:job_type => "Driver")
  end


  def alert
    if (current_user.job_type == "admin")
    @routes= Position.select("route, alert")
    else
    @route= Position.where(:route => current_user.route.route_name).first
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def menu
     @user = User.find(params[:id])
  end
  
  def assign_driver
    @bus= Bus.find(params[:bus_id])
    @user= User.find(params[:user_id])
    @route= @bus.route
    @source= Halt.where(:halt_name => @route.source).first
    if ((@user.update_attributes bus: @bus, route: @route, halt: @source) && (@bus.update_attributes bus_driver: @user.username))
      flash[:success] = "Driver Assigned To Bus"
      redirect_to buses_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :job_type, :address, :bus_id, :avatar, :password,
                                   :password_confirmation)
    end
  
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.role == 'admin'
    end
end

app/views/users/_user.html.erb
<li>
  <%#= gravatar_for user, size: 52 %>
  <%= link_to user.username, user %> | <%= link_to user.job_type, user %>
  <% if current_user.job_type== "admin" && !current_user?(user) %>&nbsp;&nbsp;
   |<%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>


 

app/views/users/alert.html.erb
<% provide(:title, 'Alerts') %>
<h1><font face="Arial" color="Red" >Alerts</font></h1>
<% if (current_user.job_type == "admin") %>
<% @routes.each do |route| %>
<font face="Arial" size="5" >
	<%= route.route %>: </font><font face="Arial" color="Blue" size="4" >
	<% if (!(route.alert == "") && !(route.alert.nil?)) %>
	<%= route.alert %>
	<% else %>
	No Alert
    <% end %>
</font><hr>
<% end %>
<% else %>
<font face="Arial" size="5" >
	<%= @route.route %>: </font><font face="Arial" color="Blue" size="4" ><%= @route.alert %></font><hr>
<% end %>

app/views/users/drivers.html.erb
<h1>Select Driver For - <%= @bus.bus_no %></h1>
<table class="table">
  <tr>
    <td>Name</td>
    <td>Alloted Bus</td>
    <td>Assign</td>
  </tr>
  <% @drivers.each do |driver| %>
  <tr>
    <td><%= driver.username %></td>
    <% if (driver.bus.nil?) %>
    <td>Not Assigned</td>
    <% else %>
    <td><%= driver.bus.bus_no %></td>
    <% end %>
    <td><%= link_to 'Select', assign_driver_bus_user_path(driver,@bus) %></td>
  </tr>
  <% end %>
</table>



app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

     <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.text_field :email %>

       <%= f.label :job_type %>
      <%= f.select :job_type, [["Employee", :Employee],["Driver", :Driver]] %>
    
       <%= f.label :address %>
      <%= f.text_field :address %>

      <%#= f.label :Select_Bus %>
      <%#= options_from_collection_for_select(Bus.all, :id, :id) %>
     <%#= collection_select(:user, :bus_id, Bus.all, :id, :id) %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>


      <%= f.submit "Save Changes", class: "btn btn-small btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All Users</h1>
<%= will_paginate %>
<ul class="users">
      <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/menu.html.erb
<div class="row">
	<div class="span4">
     <h4>
     <%= image_tag "routes.jpg", :size=> "150x150", :class=> "img-circle" %><%= link_to "Available Routes", routes_path %></h4>
    </div>
     <br><br><br>
    <div class="span4 offset6">
      <h4><%= image_tag "buses.jpg", :size=> "150x150", :class=> "img-circle" %><%= link_to "Available Buses", buses_path %><h4>
    </div>
     <br><br><br>
</div>
<div class="row">
	<div class="span4">
      <% if @user.job_type == "admin"  %>
        <h4><%= image_tag "halts.jpg", :size=> "150x150", :class=> "img-circle" %><%= link_to "All Halts", halts_path %></h4>
    </div>
        <br><br><br>
    <div class="span4 offset6">
        <h4><%= image_tag "Desert_road.jpg", :size=> "150x150", :class=> "img-circle" %><%= link_to "Add New Route", new_route_path %></h4>
        </div>
        <% end %>
        <br>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.text_field :email %>

       <%= f.label :job_type %>
      <%= f.select :job_type, [["Employee", :Employee],["Driver", :Driver]] %>
    
       <%= f.label :address %>
      <%= f.text_field :address %>

      <%#= f.label :Select_Bus %>
      <%#= options_from_collection_for_select(Bus.all, :id, :id) %>
     <%#= collection_select(:user, :bus_id, Bus.all, :id, :id) %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-small btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript">
</script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<% provide(:title, @user.email) %>
<h1>
	<%#= gravatar_for @user %>
  <% if (current_user == @user) %>
	<div class="row">
		<div class="span4"></div><div class="span4"></div><div class="span4"><font face="monotype corsiva" color=-"gray"> Hi <%= @user.email %></font></div></div><hr><% end %>
    <h4>
Name : <font face="monotype corsiva" color="#ff5fff" ><%= @user.email %></font><hr width="350">
Role : <font face="monotype corsiva" color="#ff5fff"><%= @user.role.name %></font><hr width="350">
<% if @user_halt %>
  Halt :<font face="monotype corsiva" color="#ff5fff">
    <%= @user_halt.halt.name %>
  </font><hr width="350">
<% end %>
Address :<font face="monotype corsiva" color="#ff5fff"><%= @user.address %></font>
<hr>
<% if @user.route_halt %>
My Route and Halt:
</h1>
<div style='width: 700px;'>
  <div id="directions" style='width: 700px; height: 300px;'></div>
</div>
<script type="text/javascript">
var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();

function calcRoute() {
  //var origin      = new google.maps.LatLng(19.2183, 72.9781);
  //var destination = new google.maps.LatLng(19.1512, 72.9996);
  var origin      = new google.maps.LatLng(<%= @route.s_lat.to_json %>, <%= @route.s_long.to_json %> );
  var destination = new google.maps.LatLng(<%= @route.latitude.to_json %>, <%= @route.longitude.to_json %>);
  var request = {
      origin:      origin,
      destination: destination,
      travelMode:  google.maps.TravelMode.DRIVING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    }
  });
}

calcRoute();

var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'directions'}}, function(){
  directionsDisplay.setMap(handler.getMap());

  markers = handler.addMarkers(<%=raw @hash.to_json %>);
 handler.bounds.extendWith(markers);
 handler.fitMapToBounds();

});

</script>
<% if ((current_user == @user) || (current_user.role =="admin")) %>
<h3><%= link_to "View Bus Position", user_position_path(@user,@pos) %>
  <% end %>
<% if ((current_user== @user) && (current_user.role == "driver")) %>
| <%= link_to "Broadcast", edit_position_path(@pos) %></h3>
<% end %><hr>
<h3><%= link_to "View Alert", alert_user_path %>
<% end %>