config/routes.rb
Project::Application.routes.draw do
  devise_for :users

  match 'routes/:route_id/display' => 'halts#display', via: :get, as: :display_route_halts
  match 'routes/:route_id/halts/:id/register' => 'halts#register', via: [:get,:post], as: :register_route_halt
  match 'routes/:route_id/halts/:id/remove' => 'halts#remove', via: [:get,:post], as: :remove_route_halt
  match 'routes/:route_id/buses/:bus_id/assign' => 'buses#assign', via: [:get,:post], as: :assign_bus
  match 'routes/:route_id/halts/:id/assign_halt' => 'halts#assign_halt', via: [:get,:post], as: :assign_halt_route_halt
  match 'users/:id/menu' => 'users#menu', via: :get, as: :menu_user
  match 'buses/:bus_id/users/drivers' => 'users#drivers', via: :get, as: :drivers_bus_user
  match 'users/:user_id/buses/:bus_id/assign_driver' => 'users#assign_driver', via: :get, as: :assign_driver_bus_user
  match 'users/alert' => 'users#alert', via: :get, as: :alert_user
  
  resources :positions, only: [:edit, :update, :show, :destroy]
  
  resources :buses
  
  resources :halts
  
  resources :users do
    resources :positions, only: [:show]
    resources :buses
  end

  resources :routes do
    resources :buses
    resources :halts do 
      resources :buses
    end
  end

  
  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/route.rb
class Route < ActiveRecord::Base
	has_many :route_halts, dependent: :destroy
	has_many :halts, through: :route_halts
	has_many :vehicles
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def index
    @routes = Route.all
  end

  def show
  @route = Route.find(params[:id])
  @buses = Bus.all
  end
  
  def new
  	@route = Route.new
    @pos =Position.new
  end

  def edit
    @route = Route.find(params[:id])

  end

  def update
    @route = Route.find(params[:id])
     @halts= @route.halts
     @bus= @route.bus
     @pos = Position.where(:route => @route.route_name).first
     @count = 0
    if @route.update_attributes(params[:route].permit(:route_name, :source, :destination))
       @lat= Halt.where(:halt_name => @route.source).first.latitude
       @long= Halt.where(:halt_name => @route.source).first.longitude
       @halts.each do |halt|
         halt.update_attributes route: @route
         @count = @count + 1
       end
       if((@bus.update_attributes route: @route) && (@route.update_attributes s_lat: @lat, s_long: @long) && (@pos.update_attributes route: @route))
          flash[:success] = "Route, its #{@count} halts and bus updated successfully"
          redirect_to @route
       end
     else
      render 'edit'
     end
   end

  def create
     @route = Route.new(params[:route].permit(:route_name, :source, :destination))
     @pos = Position.new route: @route
     @lat= Halt.where(:halt_name => @route.source).first.latitude
     @long= Halt.where(:halt_name => @route.source).first.longitude
     if ((@route.save) && (@route.update_attributes s_lat: @lat, s_long: @long))
      @pos = Position.new route: @route.route_name
      if (@pos.save)
        @bus=@route.bus
        @halt = Halt.where(:halt_name => @route.source).first
        if ((@halt.update_attributes route: @route, bus: @bus) && (@halt.save))
       flash[:success] = "New Route added!...Add halts and bus for it"
       redirect_to @route
        end
      end
    else
      render 'new'
    end
  end

   def destroy
    Route.find(params[:id]).destroy
    flash[:success] = "Route deleted."
    redirect_to routes_url
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/edit.html.erb
<% provide(:title, 'Edit Route') %>
<h1>Edit Route</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@route) do |f| %>
    <%#= render 'shared/error_messages_for_routes' %>

      <%= f.label :route_name %>
      <%= f.text_field :route_name %>
      
      <%= f.label :Select_Source %>
     <%= options_from_collection_for_select(Halt.all, :halt_name, :halt_name) %>
     <%= collection_select(:route, :source, Halt.all, :halt_name, :halt_name) %>

      <%= f.label :destination %>
      <%= f.text_field :destination %>


      <%= f.submit "Edit Route", class: "btn btn-large btn-primary" %>
      
    <% end %>
  </div>
</div>

app/views/routes/index.html.erb
<% provide(:title, 'All Available Routes') %>
<h1>All Available Routes</h1>
<table class="table">
  <tr>
    <th>Route Name</th>
     <th>Bus</th>
    <th>View Halts</th>
    <% if current_user.job_type == "admin"  %>
    <th>EDIT</th>
    <th>DESTROY</th>
     <th>Assign Bus</th>
    <th>Assign Halts</th>
    <% end %>
  </tr>
 
  <% @routes.each do |r| %>
    <tr>
      <td><%= r.route_name %></td>
      <td>
        <% if !(r.bus.nil?) %>
        <%= r.bus.bus_no %>
        <% else %>
        Not Assigned
        <% end %>
      </td>
      <td><%= link_to 'View Halts', display_route_halts_path(r) %></td>
      <% if current_user.job_type == "admin"  %>
       <td><%= link_to 'Edit', edit_route_path(r) %></td>
       <td><%= link_to "<i class='icon-trash icon-large'></i>".html_safe, route_path(r),
                    method: :delete, data: { confirm: 'This Route And All Its Halts Will Be Deleted!' } %></td>
       <td><%= link_to 'Assign bus', route_path(r) %></td>             
      <td><%= link_to "<i class='icon-plus-sign icon-large'></i>".html_safe, route_halts_path(r) %>
      </td>
      <% end %>
    </tr>
  <% end %>
</table><br>
<%= link_to "My Menu", menu_user_path(current_user) %>

app/views/routes/new.html.erb
<% provide(:title, 'Add New Route') %>
<h1>Add New Route</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@route) do |f| %>
    <%= render 'shared/error_messages_for_routes' %>

      <%= f.label :route_name %>
      <%= f.text_field :route_name %>

     <%= f.label :Select_Source %>
     <%= options_from_collection_for_select(Halt.all, :halt_name, :halt_name) %>
     <%= collection_select(:route, :source, Halt.all, :halt_name, :halt_name) %> 

      <%= f.label :destination %>
      <%= f.text_field :destination %>

      <%= f.submit "Add Route", class: "btn btn-small btn-primary" %>
    <% end %>
  </div>
</div>

app/views/routes/show.html.erb
<% provide(:title, @route.route_name) %>
<h1><u><font face="Monotype corsiva" color= "Blue"><%= @route.route_name %></font></u></h1><br>
  <br>
  <%= render "buses/bus_list" %>
  <hr>
  <%= link_to "Add New Bus", new_route_bus_path(@route) %>
 
