config/routes.rb
Project::Application.routes.draw do
  devise_for :users

  match 'routes/:route_id/display' => 'halts#display', via: :get, as: :display_route_halts
  match 'routes/:route_id/halts/:id/register' => 'halts#register', via: [:get,:post], as: :register_route_halt
  match 'routes/:route_id/halts/:id/remove' => 'halts#remove', via: [:get,:post], as: :remove_route_halt
  match 'routes/:route_id/buses/:bus_id/assign' => 'buses#assign', via: [:get,:post], as: :assign_bus
  match 'routes/:route_id/halts/:id/assign_halt' => 'halts#assign_halt', via: [:get,:post], as: :assign_halt_route_halt
  match 'users/:id/menu' => 'users#menu', via: :get, as: :menu_user
  match 'buses/:bus_id/users/drivers' => 'users#drivers', via: :get, as: :drivers_bus_user
  match 'users/:user_id/buses/:bus_id/assign_driver' => 'users#assign_driver', via: :get, as: :assign_driver_bus_user
  match 'users/alert' => 'users#alert', via: :get, as: :alert_user
  
  resources :positions, only: [:edit, :update, :show, :destroy]
  
  resources :buses
  
  resources :halts
  
  resources :users do
    resources :positions, only: [:show]
    resources :buses
  end

  resources :routes do
    resources :buses
    resources :halts do 
      resources :buses
    end
  end

  
  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
 
  <nav>
    <ul>
      <li><%= link_to "About",   about_path, id: "hlink" %></li>
      <li><%= link_to "Contact", contact_path, id: "hlink" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "BusTracker ©", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", root_path, id: "hlink" %></li>
              <li><%#= link_to "Help", help_path, id: "hlink" %></li>
               <% if signed_in? %>
            <li><%= link_to "Users", users_path, id: "hlink" %></li>
            <li id: "hlink" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <b><font size="3", color="red"> ACCOUNT </font></b> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "My Menu", menu_user_path(current_user) %></li>
                <li><%= link_to "My Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%#= link_to "Sign in", signin_path,  id: "hlink" %></li>
          <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  <%= render 'layouts/footer' %>
</body>
</html>